### PR TITLE
spelling

### PR DESCRIPTION
**Pull request by ripper234**

### CODE REVIEW

**Comment by genjix** [comment]
thanks for your interest, I think paypub is bigger than darkmarket yet has received no attention relatively. maybe I should've called it darkleaks :D

**Comment by HostFat** [comment]
maybe it's a good idea :D

**Comment by ripper234** [comment]
Yeah I just saw it via an unrelated reddit post the other day - great work!
While it's amusing, I don't think it would actually be the right move to name it DarkSomething.

How about giving a talk about it in conference or two?

**Comment by genjix** [comment]
good idea, I will do that!

**Pull request merged**
